resources:
- name: messenger
  type: git
  source:
    uri: https://github.com/appscode/messenger
    branch: concourse

jobs:
- name: messenger
  plan:
  - get: messenger
    trigger: true
  - task: e2e-test
    file: messenger/hack/concourse/e2e-test.yml
    privileged: true
    params:
      DOCKER_USER: ((docker_user))
      DOCKER_PASS: ((docker_pass))
      TOKEN_TO_SEND: ((hipcat_send_msg_token))
      TOKEN_TO_SEE: ((hipcat_view_msg_token))
      CA_CRT: ((ca_crt))
      CA_KEY: ((ca_key))
      CLIENT_CRT: ((client_crt))
      CLIENT_KEY: ((client_key))
